name: Java CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Download the code
        uses: actions/checkout@v4

      - name: Install Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Allow Gradle to run
        run: chmod +x gradlew

      - name: Build and Test
        run: ./gradlew build

      - name: Run the app
        run: ./gradlew run

      - name: Save the JAR file
        uses: actions/upload-artifact@v4
        with:
          name: app-jar
          path: app/build/libs/*.jar